# Generated by Django 2.2.24 on 2022-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='epassword',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
